---
--- Generated by EmmyLua(https://github.com/EmmyLua)
--- Created by Lalique.
--- DateTime: 2024/1/11 16:49
---
--比较线程标识与锁中的标识是否一致，如果一致则删除
if(redis.call('get',KEYS[1]) == ARGV[1]) then
    return redis.call('del',KEYS[1])
end
return 0